export const InternalErrorCode = {
  // USER 1-9
  USER_NOT_FOUND: 1,
  USER_MISMATCHED_PASSWORD: 2,
  USER_CONFLICT_NICKNAME: 3,
  USER_ALREADY_EXISTS: 4,

  //FRIEND 10-19
  FRIEND_REQUEST_TARGET_USER_NOT_FOUND: 10,

  //LETTER 20-29
  LETTER_NOT_FOUND: 20,
};
